#!/usr/bin/python3
#
# build_docs - Generate Anaconda documentation.
#
# Copyright (C) 2016  Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os
import subprocess
import argparse
import shutil
import multiprocessing

# package requirements:
# git
# libtool
# dnf
# python3
# python3-sphinx
# python3-nose-testconfig
# python3-lxml
# python3-dogtail

ANACONDA_DIR = "anaconda"
PYKICKSTART_DIR = "pykickstart"
BLIVET_DIR = "blivet"

ANACONDA_REPO = "https://github.com/rhinstaller/anaconda"
PYKICKSTART_REPO = "https://github.com/rhinstaller/pykickstart"
BLIVET_REPO = "https://github.com/rhinstaller/blivet"

ANACONDA_BRANCH = "master"
PYKICKSTART_BRANCH = "pykickstart-2"
BLIVET_BRANCH = "2.1-devel"

DOCS_DIR = "docs"

def init_repo(repo_folder, repo_url, branch_name=None):
    os.makedirs(repo_folder)
    if branch_name:
        command = "git clone --depth 1 --branch %s %s %s" % (branch_name, repo_url, repo_folder)
    else:
        command = "git clone --depth 1 %s %s" % (repo_url, repo_folder)

    subprocess.call(command, shell=True)

def update_repo(repo_folder, repo_url, branch=None):
    print("Updating the %s source code repository." % repo_folder)
    # make sure the repo clone exists
    if not os.path.exists(repo_folder):
        print("Initial %s source code repository initialization." % repo_folder)
        init_repo(repo_folder, repo_url, branch)
    # update the repo
    subprocess.call("git pull", shell=True, cwd=repo_folder)

def clean_anaconda():
    print("Cleaning the Anaconda source code repository.")
    subprocess.call("git reset --hard HEAD", shell=True, cwd=ANACONDA_DIR)

def install_outside_dependencies():
    subprocess.call("dnf install git libtool python3-sphinx python3-nose-testconfig python3-lxml python3-dogtail", shell=True)

def install_makefile_dependencies():
    print("installing Anaconda build and runtime dependencies")
    subprocess.call("make install-buildrequires", shell=True, cwd=ANACONDA_DIR)
    subprocess.call("make install-requires", shell=True, cwd=ANACONDA_DIR)

def build_docs(install_deps=False):
    if install_deps:
        install_outside_dependencies()
    print("Configuring Anaconda")
    # All glory to autotools!
    subprocess.call("./autogen.sh", shell=True, cwd=ANACONDA_DIR)
    subprocess.call("./configure", shell=True, cwd=ANACONDA_DIR)
    if install_deps:
        install_makefile_dependencies()
    # we also need to build the Anaconda widgets
    subprocess.call("make -j%d" % (multiprocessing.cpu_count() + 1), shell=True, cwd=ANACONDA_DIR)
    print("Generating the Anaconda documentation.")
    PYTHON_PATH = "../../blivet:../../pykickstart:../widgets:.."
    subprocess.call("PYTHONPATH=%s make html" % PYTHON_PATH, shell=True, cwd=os.path.join(ANACONDA_DIR, "docs"))

def commit_docs_update():
    print("Creating a documentation update commit.")
    subprocess.call("git add -u %s" % DOCS_DIR, shell=True)

    commit_message = "Update the Anaconda documentation"
    subprocess.call('git commit -m "%s"' % commit_message, shell=True)

def push_docs_update():
    print("Pushing a documentation update to origin.")
    subprocess.call('git push origin master', shell=True)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate Anaconda documentation.")
    parser.add_argument("--commit", action="store_true", default=False,
                        help="Commit all current changes in the generated docs repository.")
    parser.add_argument("--push", action="store_true", default=False,
                        help="Push changes in the generated docs back to origin.")
    parser.add_argument("--install-deps", action="store_true", default=False,
                        help="Automatically install dependencies for docs generation.")

    args = parser.parse_args()

    # make sure the Anaconda source code is up-to-date
    update_repo(ANACONDA_DIR, ANACONDA_REPO, ANACONDA_BRANCH)

    # also update Pykickstart
    update_repo(PYKICKSTART_DIR, PYKICKSTART_REPO, PYKICKSTART_BRANCH)

    # and blivet
    update_repo(BLIVET_DIR, BLIVET_REPO, BLIVET_BRANCH)

    # build the docs
    build_docs(install_deps=args.install_deps)

    # update the contents of the docs folder
    print("Updating the documentation folder.")
    if os.path.exists(DOCS_DIR):
        shutil.rmtree(DOCS_DIR)
    shutil.copytree(os.path.join(ANACONDA_DIR, DOCS_DIR), DOCS_DIR)

    if args.commit:
        commit_docs_update()

    if args.push:
        push_docs_update()
